<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="insert_robot" params="prefix length width height mass wheel_radius wheel_pos_z">

        <link name="${prefix}base_footprint"/>

        <link name="${prefix}base_link">
          <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <box size="${length} ${width} ${height}"/>
                <!-- <mesh filename="" scale="0.001 0.001 0.001"/> -->
              </geometry>
                <material name="yellow">
                <color rgba="0.8784 0.6627 0.6627 1.0"/>
                </material>
         </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>
              <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
              <mass value="${mass}"/>
              <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                    izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
              </inertial>
        </link>

         <gazebo reference="base_link">  
            <visual>  
                <material>
                    <ambient>0.8392 0.6314 0.0 1.0</ambient>  
                    <diffuse>0.8392 0.6314 0.0 1.0</diffuse>  
                    <specular>0.99 0.99 0.99 1.0</specular>  
                    <emissive>0.0 0.0 0.0 0.0</emissive>  
                </material>
            </visual> 
        </gazebo>

        <joint name="base_to_footprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
      </joint>
     </xacro:macro>

     <xacro:macro name="mecanum_wheel" params="side radius width pos_x pos_y pos_z mass">
            <link name="${side}_wheel_link">
                <visual>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                    <geometry>
                        <cylinder radius="${radius}" length="${width}"/>
                    </geometry>
                    <material name="blue">
                        <color rgba="0.1764 0.4588 0.8509 1.0"/>
                    </material>
                </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(2/5) * mass * (radius * radius)}" ixy="0" ixz="0"
                 iyy="${(2/5) * mass * (radius * radius)}" iyz="0"
                 izz="${(2/5) * mass * (radius * radius)}" />
      </inertial>
      
    </link>

    <gazebo reference="${side}_wheel_link">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

    <gazebo reference="${side}_wheel_link">  
      <visual>  
        <material>
          <ambient>0.1764 0.4588 0.8509 1.0</ambient>  
          <diffuse>0.1764 0.4588 0.8509 1.0</diffuse>  
          <specular>0.1764 0.4588 0.8509 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual>  
    </gazebo>
    <joint name="${side}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" />
      <parent link="base_link"/>
      <child link="${side}_wheel_link"/>
      <origin xyz="${pos_x} ${pos_y} ${pos_z}" rpy="0 0 0"/>
      <command_interface name="velocity" />
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    </xacro:macro>
</robot>